### PR TITLE
Use latest eclair with sqlite wal mode

### PR DESCRIPTION
**Pull request by pm47**
This should probably not be merged because it points to an unreleased version of eclair.

In my tests, the new sqlite config brings significant improvements.

Also, I suspect the limitation in terms of number of processes was due to the conservative default of max 30 accepted htlcs eclair.

### CODE REVIEW

**Comment by pm47** [comment]
Related to https://github.com/ACINQ/eclair/pull/1871.

**Comment by pm47** [comment]
@joostjager commit a12d090 is ready for a run 🚤

**Comment by joostjager** [comment]
Looks really good!

```
loadtest_1      | 2021-07-14T07:54:11.697Z      INFO    Speed   {"tps": 81.68428958817856, "count": 665000, "avg_latency_sec": 1.221347728044}
loadtest_1      | 2021-07-14T07:54:24.851Z      INFO    Speed   {"tps": 76.0217553890093, "count": 666000, "avg_latency_sec": 1.297248242315}
loadtest_1      | 2021-07-14T07:54:37.161Z      INFO    Speed   {"tps": 81.23427021325696, "count": 667000, "avg_latency_sec": 1.254670928563}
loadtest_1      | 2021-07-14T07:54:49.195Z      INFO    Speed   {"tps": 83.09989305408573, "count": 668000, "avg_latency_sec": 1.200546549896}
loadtest_1      | 2021-07-14T07:55:01.462Z      INFO    Speed   {"tps": 81.52775937945361, "count": 669000, "avg_latency_sec": 1.21547305595}
loadtest_1      | 2021-07-14T07:55:14.385Z      INFO    Speed   {"tps": 77.37908640270737, "count": 670000, "avg_latency_sec": 1.2922434266810001}
loadtest_1      | 2021-07-14T07:55:26.586Z      INFO    Speed   {"tps": 81.96396636080597, "count": 671000, "avg_latency_sec": 1.228921122583}
loadtest_1      | 2021-07-14T07:55:38.642Z      INFO    Speed   {"tps": 82.94430960513358, "count": 672000, "avg_latency_sec": 1.208817076528}
loadtest_1      | 2021-07-14T07:55:51.924Z      INFO    Speed   {"tps": 75.29192673915219, "count": 673000, "avg_latency_sec":
```

**Comment by pm47** [comment]
Awesome, thanks! I will update this PR when we merge the change.

**Comment by pm47** [comment]
Superseded by #8.

**Pull request closed without merging**
